<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-default credit-card-box">
            <div class="panel-heading display-table" >
                <div class="row display-tr" >
                    <h3 class="panel-title display-td" >Users</h3>
                    <a class="btn btn-success" style="float:right" href="<?=$this->url('authentication/users/new')?>">Add</a>
                </div>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-12">
                        <table class="table">
                            <?php if (count($this->users) === 0): ?>
                                <tr>
                                    <td>You haven't created any users yet.</td>
                                </tr>
                            <?php
                            else:
                                foreach ($this->users as $user):
                                    /** @var \ConferenceTools\Authentication\Domain\User\ReadModel\User $user */
                                    ?>
                                    <tr>
                                        <td class="col-md-6 col-xs-6">
                                            <span class="col-xs-12 col-md-6"><?= $user->getUsername() ?></span>
                                        </td>
                                        <td class="col-md-3 col-xs-3">
                                            <a class="btn btn-danger" href="<?=$this->url('authentication/users/permissions', ['user' => $user->getUsername()])?>">
                                                Edit permissions
                                            </a>
                                        </td>
                                    </tr>
                                <?php
                                endforeach;
                            endif;
                            ?>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>