<div class="row">
    <div class="col-md-12">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Users</div>
            </div>
            <div class="card-body ">
                <table class="table table-hover table-in-card">
                    <thead>
                        <tr>
                            <th>Username</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->users as $user):
                            /** @var \ConferenceTools\Authentication\Domain\User\ReadModel\User $user */
                            ?>
                            <tr>
                                <td>
                                    <?= $user->getUsername() ?>
                                </td>
                                <td>
                                    <a class="btn btn-danger" href="<?=$this->url('authentication/users/permissions', ['user' => $user->getUsername()])?>">
                                        Edit permissions
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>